services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: javaDocker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: java_backend_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/javaDocker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./user_interface
    container_name: react_frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./user_interface:/app
      - /app/node_modules
volumes:
  postgres_data:
